"""reset tables for testing migration

Revision ID: 0c4d87d1bc1c
Revises: 780b0bf8d4d2
Create Date: 2025-05-13 09:49:54.896804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c4d87d1bc1c'
down_revision: Union[str, None] = '780b0bf8d4d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_quizzes_id', table_name='quizzes')
    op.drop_table('quizzes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quizzes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='quizzes_pkey')
    )
    op.create_index('ix_quizzes_id', 'quizzes', ['id'], unique=False)
    # ### end Alembic commands ###
